spring.application.name=ghost-employer
server.port=8080

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1920
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- DEEPSEEK CLOUD (EXCLUSIF) ---
spring.ai.openai.base-url=https://api.deepseek.com
spring.ai.openai.api-key=sk-f0dcd70eb62b4afdb36a740cb575de35
spring.ai.openai.chat.options.model=deepseek-chat

# --- PIXABAY (images par mot-clé) ---
# Inscription gratuite sur https://pixabay.com/api/docs/
pixabay.api.key=55615848-b532cf21838a30eb2ea6552df


